-- 1. Create Category Sections table (Top-level)
CREATE TABLE IF NOT EXISTS category_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    icon TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE,
    image_url TEXT
);


-- 2. Create Category Sub-sections table (Second-level)
-- Includes CASCADE DELETE so deleting a section removes its child sub-sections automatically.
CREATE TABLE IF NOT EXISTS category_subsections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT REFERENCES category_sections(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    image_url TEXT,
    UNIQUE(section_id, name)
);


-- 3. Enable RLS (Optional, recommended for production)
ALTER TABLE category_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE category_subsections ENABLE ROW LEVEL SECURITY;

-- 4. Set Policies for Public Access (Selecting)
DROP POLICY IF EXISTS "Allow public select on sections" ON category_sections;
DROP POLICY IF EXISTS "Allow public select on subsections" ON category_subsections;
CREATE POLICY "Allow public select on sections" ON category_sections FOR SELECT USING (true);
CREATE POLICY "Allow public select on subsections" ON category_subsections FOR SELECT USING (true);

-- 5. Set Policies for Admin Access (ALL)
DROP POLICY IF EXISTS "Allow admin all on sections" ON category_sections;
DROP POLICY IF EXISTS "Allow admin all on subsections" ON category_subsections;
CREATE POLICY "Allow admin all on sections" ON category_sections USING (true);
CREATE POLICY "Allow admin all on subsections" ON category_subsections USING (true);


-- 6. Legacy Migration Function (Optional, for 'Sync Legacy' button)
CREATE OR REPLACE FUNCTION sync_legacy_categories() 
RETURNS void AS $$
BEGIN
    INSERT INTO category_sections (name, icon)
    SELECT name, icon FROM categories WHERE parent_id IS NULL
    ON CONFLICT (name) DO NOTHING;

    INSERT INTO category_subsections (section_id, name)
    SELECT s.id, c.name
    FROM categories c
    JOIN category_sections s ON s.name = (SELECT name FROM categories WHERE id = c.parent_id)
    WHERE c.parent_id IS NOT NULL
    ON CONFLICT (section_id, name) DO NOTHING;
END;
$$ LANGUAGE plpgsql;

-- 7. SEED DATA (Pre-populating with common categories)
-- Run this to get started with a professional category tree.

-- Add Sections
INSERT INTO category_sections (name, icon) VALUES
('Fashion', '👕'),
('Electronics', '📱'),
('Grocery', '🥦'),
('Home & Decor', '🏠'),
('Beauty & Health', '💄'),
('Others', '📦')
ON CONFLICT (name) DO NOTHING;

-- Add Sub-sections for Fashion
INSERT INTO category_subsections (section_id, name)
SELECT id, 'Men''s Wear' FROM category_sections WHERE name = 'Fashion' UNION ALL
SELECT id, 'Women''s Wear' FROM category_sections WHERE name = 'Fashion' UNION ALL
SELECT id, 'Kids'' Wear' FROM category_sections WHERE name = 'Fashion' UNION ALL
SELECT id, 'Footwear' FROM category_sections WHERE name = 'Fashion'
ON CONFLICT (section_id, name) DO NOTHING;

-- Add Sub-sections for Electronics
INSERT INTO category_subsections (section_id, name)
SELECT id, 'Mobiles' FROM category_sections WHERE name = 'Electronics' UNION ALL
SELECT id, 'Laptops' FROM category_sections WHERE name = 'Electronics' UNION ALL
SELECT id, 'Accessories' FROM category_sections WHERE name = 'Electronics'
ON CONFLICT (section_id, name) DO NOTHING;

-- Add Sub-sections for Grocery
INSERT INTO category_subsections (section_id, name)
SELECT id, 'Fruits & Vegetables' FROM category_sections WHERE name = 'Grocery' UNION ALL
SELECT id, 'Dairy & Eggs' FROM category_sections WHERE name = 'Grocery' UNION ALL
SELECT id, 'Snacks' FROM category_sections WHERE name = 'Grocery'
ON CONFLICT (section_id, name) DO NOTHING;


