-- Create Home Page Categories table
CREATE TABLE IF NOT EXISTS home_page_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE
);

-- Enable RLS
ALTER TABLE home_page_categories ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "Allow public select on home_categories" ON home_page_categories;
CREATE POLICY "Allow public select on home_categories" ON home_page_categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admin all on home_categories" ON home_page_categories;
CREATE POLICY "Allow admin all on home_categories" ON home_page_categories USING (true);

-- Seed initial 4 slots
INSERT INTO home_page_categories (name) VALUES 
('Men'), 
('Women'), 
('Kids'), 
('Others')
ON CONFLICT (name) DO NOTHING;
