-- 1. Create Category Sub-subsections table (Third-level)
CREATE TABLE IF NOT EXISTS public.category_sub_subsections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subsection_id BIGINT REFERENCES public.category_subsections(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(subsection_id, name)
);

-- 2. Enable RLS
ALTER TABLE public.category_sub_subsections ENABLE ROW LEVEL SECURITY;

-- 3. Set Policies
DROP POLICY IF EXISTS "Allow public select on sub_subsections" ON public.category_sub_subsections;
DROP POLICY IF EXISTS "Allow admin all on sub_subsections" ON public.category_sub_subsections;

CREATE POLICY "Allow public select on sub_subsections" ON public.category_sub_subsections 
    FOR SELECT USING (true);

CREATE POLICY "Allow admin all on sub_subsections" ON public.category_sub_subsections 
    USING (true);

-- 4. Seed Sub-subsections under Men's Wear
-- Inserts Shirt, T-Shirt, Jacket under the 'Men''s Wear' subsection
INSERT INTO public.category_sub_subsections (subsection_id, name)
SELECT id, 'Shirt' FROM public.category_subsections WHERE name = 'Men''s Wear' UNION ALL
SELECT id, 'T-Shirt' FROM public.category_subsections WHERE name = 'Men''s Wear' UNION ALL
SELECT id, 'Jacket' FROM public.category_subsections WHERE name = 'Men''s Wear'
ON CONFLICT (subsection_id, name) DO NOTHING;
